name: Signal
description: Signal Messenger mit persistenter Session, Web-UI, REST-API und Webhook für Home Assistant
version: "1.0.27"
slug: signal
url: https://github.com/LuckyTriple7/HA-AddOns

arch:
  - amd64
  - aarch64

startup: application
boot: manual
init: false

ingress: true
ingress_port: 17777
panel_icon: phu:signal
panel_title: Signal

ports:
  17777/tcp: 17777

ports_description:
  17777/tcp: Signal Web-UI und REST-API

options:
  dark_mode: false
  native_mode: true
  phone_number: ""
  webhook_incoming: ""

schema:
  dark_mode: bool
  native_mode: bool
  phone_number: str?
  webhook_incoming: str?
