#!/usr/bin/env python3
"""Generates the nginx reverse-proxy config from /data/options.json at startup."""
import json
import os
import subprocess

CONFIG_PATH = '/data/options.json'
NGINX_CONF   = '/etc/nginx/http.d/messenger-portal.conf'


def detect_gateway() -> str:
    """Read the default gateway from the kernel routing table."""
    try:
        out = subprocess.check_output(['ip', 'route', 'show', 'default'],
                                      text=True, stderr=subprocess.DEVNULL)
        # e.g. "default via 172.30.32.2 dev eth0"
        for token, value in zip(out.split(), out.split()[1:]):
            if token == 'via':
                return value
    except Exception:
        pass
    return '172.30.32.2'


def proxy_block(slug: str, host: str, port: int) -> str:
    prefix = f'/proxy/{slug}/'
    return f"""
    # ── {slug} ──────────────────────────────────────────
    location {prefix} {{
        auth_request /auth-check;
        error_page 401 = @login_redirect;

        proxy_pass          http://{host}:{port}/;
        proxy_http_version  1.1;
        proxy_set_header    Host              $http_host;
        proxy_set_header    X-Real-IP         $remote_addr;
        proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto $scheme;

        # WebSocket
        proxy_set_header    Upgrade    $http_upgrade;
        proxy_set_header    Connection $connection_upgrade;
        proxy_read_timeout  86400s;
        proxy_send_timeout  86400s;

        # Rewrite absolute paths in HTML/JS responses
        sub_filter_once  off;
        sub_filter_types text/html text/javascript application/javascript application/json;
        sub_filter 'href="/'   'href="{prefix}';
        sub_filter 'src="/'    'src="{prefix}';
        sub_filter 'action="/' 'action="{prefix}';
        sub_filter "href='/"   "href='{prefix}";
        sub_filter "src='/"    "src='{prefix}";
        sub_filter 'fetch("/'  'fetch("{prefix}';
        sub_filter "fetch('/"  "fetch('{prefix}";
        sub_filter '"url":"/'  '"url":"{prefix}';
        sub_filter 'url: "/'   'url: "{prefix}';
        sub_filter "url: '/"   "url: '{prefix}";

        # Cookie path rewrite so session cookies work under the proxy prefix
        proxy_cookie_path / {prefix};
    }}
"""


def main():
    try:
        with open(CONFIG_PATH) as f:
            config = json.load(f)
    except Exception as e:
        print(f'[WARN] Could not read {CONFIG_PATH}: {e} – using defaults')
        config = {}

    configured = config.get('internal_host', '').strip()
    if configured:
        host = configured
        print(f'[INFO] internal_host aus Config: {host}')
    else:
        host = detect_gateway()
        print(f'[INFO] internal_host auto-erkannt (Gateway): {host}')
    messengers = [m for m in config.get('messengers', []) if m.get('enabled', True)]

    proxy_blocks = ''.join(
        proxy_block(m['icon'].lower(), host, m['port'])
        for m in messengers
        if m.get('icon') and m.get('port')
    )

    conf = f"""# Auto-generated by gen_nginx.py – do not edit manually

map $http_upgrade $connection_upgrade {{
    default  upgrade;
    ''       close;
}}

server {{
    listen 17770;

    # ── Internal session check ───────────────────────────
    location = /auth-check {{
        internal;
        proxy_pass              http://127.0.0.1:5000/auth-check;
        proxy_pass_request_body off;
        proxy_set_header        Content-Length  "";
        proxy_set_header        Cookie          $http_cookie;
        proxy_set_header        X-Real-IP       $remote_addr;
    }}

    location @login_redirect {{
        return 302 /login;
    }}

    # ── Flask app (login, portal, static) ───────────────
    location / {{
        proxy_pass         http://127.0.0.1:5000;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }}
{proxy_blocks}
}}
"""

    os.makedirs(os.path.dirname(NGINX_CONF), exist_ok=True)
    with open(NGINX_CONF, 'w') as f:
        f.write(conf)
    print(f'[INFO] nginx config written → {NGINX_CONF}')
    for m in messengers:
        print(f'[INFO]   /proxy/{m["icon"].lower()}/ → http://{host}:{m["port"]}/')


if __name__ == '__main__':
    main()
