name: Nextcloud
description: Nextcloud – Private Cloud direkt in Home Assistant, mit SMB-Netzwerkspeicher-Unterstützung
version: "1.0.18"
slug: nextcloud
url: https://github.com/LuckyTriple7/HA-AddOns

arch:
  - amd64

startup: application
boot: manual
init: false

image: "ghcr.io/luckytriple7/nextcloud"

panel_icon: mdi:console
panel_title: Nextcloud Terminal
webui: https://[HOST]:[PORT:7443]

ingress: true
ingress_port: 7681

ports:
  443/tcp: 7443

ports_description:
  443/tcp: Nextcloud HTTPS

privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH

map:
  - addon_config:rw
  - share:rw
  - media:ro
  - ssl

apparmor: true

options:
  PUID: 1000
  PGID: 1000
  TZ: "Europe/Berlin"
  trusted_domains: ""
  trusted_proxies: "172.30.32.0/23"
  default_phone_region: "DE"
  enable_thumbnails: true
  memory_limit: "512M"
  upload_max_filesize: "512M"
  post_max_size: "512M"
  opcache_memory_consumption: 256
  disable_updates: false
  maintenance_window_start: 1
  loglevel: 3
  skeletondirectory: ""
  trashbin_retention_obligation: "auto, 30"
  versions_retention_obligation: "auto, 30"
  update_wopi_ip: false
  mariadb_discovery: false
  smb_1_server: ""
  smb_1_share: ""
  smb_1_user: ""
  smb_1_password: ""
  smb_2_server: ""
  smb_2_share: ""
  smb_2_user: ""
  smb_2_password: ""
  smb_3_server: ""
  smb_3_share: ""
  smb_3_user: ""
  smb_3_password: ""

schema:
  PUID: int
  PGID: int
  TZ: str?
  trusted_domains: str?
  trusted_proxies: str?
  default_phone_region: match([A-Z]{2})?
  enable_thumbnails: bool
  memory_limit: str?
  upload_max_filesize: str?
  post_max_size: str?
  opcache_memory_consumption: int?
  disable_updates: bool
  maintenance_window_start: int
  loglevel: int
  skeletondirectory: str?
  trashbin_retention_obligation: str?
  versions_retention_obligation: str?
  update_wopi_ip: bool
  mariadb_discovery: bool
  smb_1_server: str?
  smb_1_share: str?
  smb_1_user: str?
  smb_1_password: str?
  smb_2_server: str?
  smb_2_share: str?
  smb_2_user: str?
  smb_2_password: str?
  smb_3_server: str?
  smb_3_share: str?
  smb_3_user: str?
  smb_3_password: str?
