"""Bot/crawler protection test: fetch a URL under a chosen identity and see
whether the response is a known bot-challenge or WAF block page instead of
the real content -- Anubis, Cloudflare's challenge, and a handful of
well-documented WAF vendors.

This runs no browser and executes no JavaScript -- it only judges the
first response, exactly what a real crawler that also doesn't run a
browser would see. Anubis specifically requires JS execution to pass, so a
real deployment SHOULD show its challenge to almost any tool built this
way, this one included -- confirmed live: even a plain requests-style call
with an ordinary desktop-browser User-Agent still gets the challenge, since
Anubis judges JS capability, not the UA string.

Anubis's markers were confirmed live against its own reference deployment
(anubis.techaro.lol, which serves its own challenge page to non-browser
clients): the exact title, its "/.within.website/x/" asset path, and its
"*-anubis-cookie-verification-*" cookie name. Cloudflare's challenge title
and its "/cdn-cgi/challenge-platform/" script path are long-stable, widely
documented signatures. The remaining WAF entries are the same kind of
published block-page text used by open WAF-fingerprinting tools -- not
independently re-verified against a live deployment of each one here, so a
match there is a strong hint, not a certainty.

Deliberately excluded: matching on a vendor's tracking/sensor cookie alone
(Akamai's _abck, Datadome's own cookie, PerimeterX's _px*, Cloudflare's
__cf_bm). Those get set on perfectly normal, unblocked visits too -- they
say "this site uses that vendor's bot-management product", not "this
request just got blocked", and conflating the two would cry wolf on every
ordinary page load a bot-management product happens to sit in front of.
"""

import dataclasses
import html
import re

import httpcheck
from netcore import Context, http_get

MAX_BYTES = 256 * 1024

# A handful of ready-made identities, since the whole point is testing as
# a specific crawler rather than as this tool's own default UA (which is
# already about as bot-like as it gets, having no browser behind it at
# all). Exact strings as published by the operators themselves.
IDENTITIES = {
    'default': None,  # ctx.user_agent as-is (NetToolbox's own)
    'googlebot': 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
    'bingbot': 'Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
    'gptbot': 'Mozilla/5.0 (compatible; GPTBot/1.2; +https://openai.com/gptbot)',
    'claudebot': 'ClaudeBot/1.0 (+https://www.anthropic.com/claudebot)',
    'ccbot': 'CCBot/2.0 (+http://commoncrawl.org/faq/)',
    'browser': ('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36'),
}

# name, category ('pow' proof-of-work · 'challenge' JS/interactive ·
# 'waf' block page), site (the product's own home, for the finding text),
# and the markers themselves -- any one hit counts as a match, more hits
# raise confidence.
SIGNATURES = (
    {'name': 'Anubis', 'category': 'pow', 'site': 'anubis.techaro.lol',
     'title': "Making sure you're not a bot!",
     'body': ('/.within.website/x/',),
     'cookie': ('anubis-cookie-verification',)},
    {'name': 'Cloudflare Challenge', 'category': 'challenge', 'site': 'cloudflare.com',
     'title': 'Just a moment...',
     'body': ('/cdn-cgi/challenge-platform/',),
     'header': (('cf-mitigated', r'challenge'),)},
    {'name': 'Cloudflare', 'category': 'waf', 'site': 'cloudflare.com',
     'title': 'Attention Required! | Cloudflare',
     'body': ('Sorry, you have been blocked',)},
    {'name': 'Imperva Incapsula', 'category': 'waf', 'site': 'imperva.com',
     'body': ('Incapsula incident ID', 'Request unsuccessful. Incapsula')},
    {'name': 'Sucuri Firewall', 'category': 'waf', 'site': 'sucuri.net',
     'body': ('Sucuri WebSite Firewall', 'Access Denied - Sucuri Website Firewall')},
    {'name': 'AWS WAF / CloudFront', 'category': 'waf', 'site': 'aws.amazon.com/waf',
     'body': ('ERROR: The request could not be satisfied',),
     'header': (('server', r'^CloudFront$'),)},
    {'name': 'ModSecurity', 'category': 'waf', 'site': 'modsecurity.org',
     'body': ('This error was generated by Mod_Security',)},
)


def _matches(sig: dict, title: str, body: str, headers: dict, cookies: list) -> list:
    hit = []
    if 'title' in sig and sig['title'].lower() in title.lower():
        hit.append('title')
    for needle in sig.get('body', ()):
        if needle.lower() in body.lower():
            hit.append('body:' + needle[:30])
            break
    for name, pattern in sig.get('header', ()):
        if re.search(pattern, headers.get(name, ''), re.I):
            hit.append('header:' + name)
    for needle in sig.get('cookie', ()):
        if any(needle.lower() in c.lower() for c in cookies):
            hit.append('cookie:' + needle)
    return hit


def check_bot_protection(ctx: Context, target: str, identity: str) -> dict:
    # A known key picks one of the ready-made identities; anything else is
    # taken as a literal custom User-Agent string (the "own text" option in
    # the UI never sends the word "custom" itself, just what was typed).
    if identity in IDENTITIES:
        user_agent = IDENTITIES[identity]
    else:
        user_agent = (identity or '').strip()[:200] or None
    fetch_ctx = ctx if user_agent is None else dataclasses.replace(ctx, user_agent=user_agent)

    start_url = httpcheck.normalise_url(target)
    chain = httpcheck.follow_redirects(fetch_ctx, start_url)
    final_url = chain[-1]['url']
    resp = http_get(fetch_ctx, final_url, max_bytes=MAX_BYTES, accept='text/html,*/*')

    body = resp.get('body') or ''
    title_m = re.search(r'<title[^>]*>(.*?)</title>', body, re.I | re.S)
    # "Making sure you&#39;re not a bot!" -- the apostrophe comes back
    # entity-escaped, and a literal-quote match against that would just
    # silently miss every time.
    title = html.unescape(title_m.group(1).strip()) if title_m else ''

    matches = []
    for sig in SIGNATURES:
        hit = _matches(sig, title, body, resp.get('headers') or {}, resp.get('cookies') or [])
        if hit:
            matches.append({'name': sig['name'], 'category': sig['category'],
                            'site': sig['site'], 'markers': hit})

    return {
        'final_url': final_url, 'status': resp.get('status', 0),
        'identity': identity, 'user_agent': fetch_ctx.user_agent,
        'title': title[:200], 'bytes': resp.get('bytes', 0),
        'redirects': len(chain) - 1, 'detected': matches,
    }
