"""Fingerprint-Tabelle für die Technik-Erkennung (nettech.py).

Reine Daten, keine Logik -- damit eine neue Technik eine Zeile ist und kein
Eingriff in die Auswertung. Jede Regel beschreibt *eine* Technik über die
Stellen, an denen sie sich in einer ausgelieferten Antwort verrät:

    'headers'  ((Header-Name, Regex), ...)   -- Antwort-Header
    'meta'     ((Meta-Name,   Regex), ...)   -- <meta name=... content=...>
    'cookie'   (Regex, ...)                  -- Name eines Set-Cookie
    'cookie_value' ((Cookie-Name, Regex), ...) -- Wert eines Set-Cookie
    'script'   (Regex, ...)                  -- src/href der eingebundenen Dateien
    'html'     (Regex, ...)                  -- Rohtext der Seite
    'url'      (Regex, ...)                  -- die finale Adresse selbst
    'implies'  (Name, ...)                   -- was mit dieser Technik zwingend läuft

Die Regexe werden mit re.I gegen fremde Inhalte laufen gelassen. Sie sind
deshalb bewusst kurz gehalten und enthalten keine verschachtelten
Wiederholungen -- ein Muster wie (a+)+ wäre auf einer präparierten Seite ein
Selbstschuss (ReDoS). Eine Gruppe namens `v` liefert, wenn vorhanden, die
Version.

Erkennung ist Indizienarbeit, kein Beweis: Header lassen sich frei setzen,
und was erst JavaScript im Browser nachlädt, steht hier nirgends. Wie sicher
ein Treffer ist, entscheidet nettech.py anhand der Fundstelle.
"""

# ── Web-Technik ──────────────────────────────────────────────────────────────

RULES = (
    # -- CMS ------------------------------------------------------------
    {'name': 'WordPress', 'cat': 'cms', 'site': 'wordpress.org',
     'meta': (('generator', r'WordPress(?:\s+(?P<v>[\d.]+))?'),),
     'script': (r'/wp-content/', r'/wp-includes/'),
     'html': (r'/wp-content/', r'/wp-json/'),
     'cookie': (r'^wordpress_', r'^wp-settings-'),
     'implies': ('PHP',)},
    {'name': 'Joomla', 'cat': 'cms', 'site': 'joomla.org',
     'meta': (('generator', r'Joomla!?(?:\s*(?P<v>[\d.]+))?'),),
     'script': (r'/media/jui/', r'/media/system/js/'),
     'cookie': (r'^joomla_',),
     'implies': ('PHP',)},
    {'name': 'Drupal', 'cat': 'cms', 'site': 'drupal.org',
     'headers': (('x-generator', r'Drupal(?:\s*(?P<v>[\d.]+))?'),),
     'meta': (('generator', r'Drupal(?:\s*(?P<v>[\d.]+))?'),),
     'script': (r'/sites/(?:all|default)/', r'/core/misc/drupal\.js'),
     'html': (r'Drupal\.settings', r'data-drupal-'),
     'implies': ('PHP',)},
    {'name': 'TYPO3', 'cat': 'cms', 'site': 'typo3.org',
     'meta': (('generator', r'TYPO3(?:\s*(?P<v>[\d.]+))?'),),
     'script': (r'/typo3temp/', r'/typo3conf/', r'/_assets/[0-9a-f]{16,}/'),
     'implies': ('PHP',)},
    {'name': 'Contao', 'cat': 'cms', 'site': 'contao.org',
     'meta': (('generator', r'Contao(?:\s+Open Source CMS)?'),),
     'script': (r'/assets/contao/',), 'implies': ('PHP', 'Symfony')},
    {'name': 'Ghost', 'cat': 'cms', 'site': 'ghost.org',
     'meta': (('generator', r'Ghost(?:\s*(?P<v>[\d.]+))?'),),
     'script': (r'/assets/built/', r'ghost/portal')},
    {'name': 'Craft CMS', 'cat': 'cms', 'site': 'craftcms.com',
     'headers': (('x-powered-by', r'Craft CMS'),),
     'cookie': (r'^CraftSessionId',), 'implies': ('PHP', 'Yii')},
    {'name': 'Statamic', 'cat': 'cms', 'site': 'statamic.com',
     'headers': (('x-statamic-resource', r'.'),), 'implies': ('Laravel',)},
    {'name': 'Kirby', 'cat': 'cms', 'site': 'getkirby.com',
     'cookie': (r'^kirby_session',), 'implies': ('PHP',)},
    {'name': 'Wix', 'cat': 'cms', 'site': 'wix.com',
     'headers': (('x-wix-request-id', r'.'),),
     'meta': (('generator', r'Wix\.com'),),
     'script': (r'static\.parastorage\.com',)},
    {'name': 'Squarespace', 'cat': 'cms', 'site': 'squarespace.com',
     'headers': (('x-servedby', r'squarespace'),),
     'script': (r'static1?\.squarespace\.com',),
     'html': (r'Static\.SQUARESPACE_CONTEXT',)},
    {'name': 'Webflow', 'cat': 'cms', 'site': 'webflow.com',
     'meta': (('generator', r'Webflow'),),
     'script': (r'assets(?:-global)?\.website-files\.com',),
     'html': (r'data-wf-(?:page|site)',)},
    {'name': 'Jimdo', 'cat': 'cms', 'site': 'jimdo.com',
     'script': (r'assets\.jimstatic\.com', r'\.jimdo(?:site)?\.com'),
     'cookie': (r'^jimdo',)},
    {'name': 'HubSpot CMS', 'cat': 'cms', 'site': 'hubspot.com',
     'headers': (('x-hs-hub-id', r'.'),),
     'script': (r'\.hs-sites\.com', r'js\.hs-scripts\.com')},
    {'name': 'Sitecore', 'cat': 'cms', 'site': 'sitecore.com',
     'cookie': (r'^SC_ANALYTICS_GLOBAL_COOKIE',), 'implies': ('ASP.NET',)},
    {'name': 'Adobe Experience Manager', 'cat': 'cms', 'site': 'adobe.com',
     'script': (r'/etc\.clientlibs/', r'/etc/designs/'),
     'html': (r'cq:template',)},
    {'name': 'Plone', 'cat': 'cms', 'site': 'plone.org',
     'meta': (('generator', r'Plone(?:\s*(?P<v>[\d.]+))?'),),
     'implies': ('Python',)},
    {'name': 'Concrete CMS', 'cat': 'cms', 'site': 'concretecms.org',
     'meta': (('generator', r'concrete5|Concrete CMS'),),
     'cookie': (r'^CONCRETE5',), 'implies': ('PHP',)},
    {'name': 'MODX', 'cat': 'cms', 'site': 'modx.com',
     'headers': (('x-powered-by', r'MODX'),),
     'meta': (('generator', r'MODX'),), 'implies': ('PHP',)},
    {'name': 'Grav', 'cat': 'cms', 'site': 'getgrav.org',
     'meta': (('generator', r'GravCMS'),), 'implies': ('PHP',)},
    {'name': 'DNN', 'cat': 'cms', 'site': 'dnnsoftware.com',
     'cookie': (r'^dnn_IsMobile', r'^DNNPersonalization'),
     'implies': ('ASP.NET',)},
    {'name': 'Strapi', 'cat': 'cms', 'site': 'strapi.io',
     'headers': (('x-powered-by', r'Strapi'),), 'implies': ('Node.js',)},

    # -- Shop -----------------------------------------------------------
    {'name': 'WooCommerce', 'cat': 'shop', 'site': 'woocommerce.com',
     'meta': (('generator', r'WooCommerce(?:\s+(?P<v>[\d.]+))?'),),
     'script': (r'/plugins/woocommerce/',),
     'cookie': (r'^woocommerce_', r'^wp_woocommerce_session'),
     'implies': ('WordPress',)},
    {'name': 'Shopify', 'cat': 'shop', 'site': 'shopify.com',
     'headers': (('x-shopify-stage', r'.'), ('x-shopid', r'.')),
     'script': (r'cdn\.shopify\.com', r'cdn\.shopifycloud\.com'),
     'cookie': (r'^_shopify_', r'^_secure_session_id'),
     'html': (r'Shopify\.theme',)},
    {'name': 'Adobe Commerce (Magento)', 'cat': 'shop', 'site': 'magento.com',
     'cookie': (r'^X-Magento-Vary', r'^mage-cache-'),
     'script': (r'/static/version\d+/', r'/mage/'),
     'html': (r'Magento_PageCache|/pub/static/',), 'implies': ('PHP',)},
    {'name': 'Shopware', 'cat': 'shop', 'site': 'shopware.com',
     'headers': (('sw-invalidation-states', r'.'),),
     'meta': (('generator', r'Shopware'),),
     'script': (r'/bundles/storefront/', r'/widgets/'),
     'cookie': (r'^session-\d',), 'implies': ('PHP', 'Symfony')},
    {'name': 'PrestaShop', 'cat': 'shop', 'site': 'prestashop.com',
     'meta': (('generator', r'PrestaShop'),),
     'cookie': (r'^PrestaShop-',), 'implies': ('PHP',)},
    {'name': 'OpenCart', 'cat': 'shop', 'site': 'opencart.com',
     'html': (r'catalog/view/theme',), 'cookie': (r'^OCSESSID',),
     'implies': ('PHP',)},
    {'name': 'BigCommerce', 'cat': 'shop', 'site': 'bigcommerce.com',
     'script': (r'cdn\d*\.bigcommerce\.com',),
     'cookie': (r'^SHOP_SESSION_TOKEN',)},
    {'name': 'JTL-Shop', 'cat': 'shop', 'site': 'jtl-software.de',
     'meta': (('generator', r'JTL-Shop'),), 'cookie': (r'^JTLSHOP',),
     'implies': ('PHP',)},
    {'name': 'OXID eShop', 'cat': 'shop', 'site': 'oxid-esales.com',
     'cookie': (r'^sid_key', r'^oxid'), 'html': (r'/out/pictures/',),
     'implies': ('PHP',)},
    {'name': 'Salesforce Commerce Cloud', 'cat': 'shop', 'site': 'salesforce.com',
     'script': (r'/on/demandware\.static/',),
     'cookie': (r'^dwsid', r'^dwanonymous_')},
    {'name': 'Ecwid', 'cat': 'shop', 'site': 'ecwid.com',
     'script': (r'app\.ecwid\.com',)},
    {'name': 'Snipcart', 'cat': 'shop', 'site': 'snipcart.com',
     'script': (r'cdn\.snipcart\.com',)},

    # -- Framework / Rendering ------------------------------------------
    {'name': 'Next.js', 'cat': 'framework', 'site': 'nextjs.org',
     'headers': (('x-powered-by', r'Next\.js(?:\s*(?P<v>[\d.]+))?'),),
     'script': (r'/_next/static/',), 'html': (r'__NEXT_DATA__',),
     'implies': ('React', 'Node.js')},
    {'name': 'Nuxt', 'cat': 'framework', 'site': 'nuxt.com',
     'meta': (('generator', r'Nuxt(?:\s*(?P<v>[\d.]+))?'),),
     'script': (r'/_nuxt/',), 'html': (r'__NUXT__|__nuxt',),
     'implies': ('Vue.js',)},
    {'name': 'Gatsby', 'cat': 'framework', 'site': 'gatsbyjs.com',
     'meta': (('generator', r'Gatsby(?:\s*(?P<v>[\d.]+))?'),),
     'html': (r'___gatsby',), 'implies': ('React',)},
    {'name': 'Astro', 'cat': 'framework', 'site': 'astro.build',
     'meta': (('generator', r'Astro(?:\s*v?(?P<v>[\d.]+))?'),),
     'html': (r'astro-island|data-astro-',)},
    {'name': 'SvelteKit', 'cat': 'framework', 'site': 'kit.svelte.dev',
     'html': (r'__sveltekit_',), 'script': (r'/_app/immutable/',),
     'implies': ('Svelte',)},
    {'name': 'Remix', 'cat': 'framework', 'site': 'remix.run',
     'html': (r'__remixContext',), 'implies': ('React',)},
    {'name': 'Hugo', 'cat': 'framework', 'site': 'gohugo.io',
     'meta': (('generator', r'Hugo(?:\s*(?P<v>[\d.]+))?'),)},
    {'name': 'Jekyll', 'cat': 'framework', 'site': 'jekyllrb.com',
     'meta': (('generator', r'Jekyll(?:\s*v?(?P<v>[\d.]+))?'),)},
    {'name': 'Eleventy', 'cat': 'framework', 'site': '11ty.dev',
     'meta': (('generator', r'Eleventy(?:\s*v?(?P<v>[\d.]+))?'),)},
    {'name': 'Docusaurus', 'cat': 'framework', 'site': 'docusaurus.io',
     'meta': (('generator', r'Docusaurus(?:\s*v?(?P<v>[\d.]+))?'),),
     'implies': ('React',)},
    {'name': 'VitePress', 'cat': 'framework', 'site': 'vitepress.dev',
     'meta': (('generator', r'VitePress(?:\s*v?(?P<v>[\d.]+))?'),),
     'implies': ('Vue.js',)},
    # Nur laravel_session: XSRF-TOKEN setzen auch Angular-Backends und
    # andere PHP-Frameworks, das waere kein Fingerabdruck, sondern Raten.
    {'name': 'Laravel', 'cat': 'framework', 'site': 'laravel.com',
     'cookie': (r'^laravel_session',), 'implies': ('PHP',)},
    {'name': 'Symfony', 'cat': 'framework', 'site': 'symfony.com',
     'headers': (('x-debug-token-link', r'.'),),
     'cookie': (r'^symfony',), 'implies': ('PHP',)},
    {'name': 'CodeIgniter', 'cat': 'framework', 'site': 'codeigniter.com',
     'cookie': (r'^ci_session',), 'implies': ('PHP',)},
    {'name': 'CakePHP', 'cat': 'framework', 'site': 'cakephp.org',
     'cookie': (r'^CAKEPHP',), 'implies': ('PHP',)},
    {'name': 'Django', 'cat': 'framework', 'site': 'djangoproject.com',
     'cookie': (r'^csrftoken', r'^django_language'),
     'html': (r'/static/admin/css/base\.css',), 'implies': ('Python',)},
    {'name': 'Ruby on Rails', 'cat': 'framework', 'site': 'rubyonrails.org',
     'headers': (('x-runtime', r'^[\d.]+$'),),
     'meta': (('csrf-param', r'authenticity_token'),),
     'cookie': (r'^_session_id',), 'implies': ('Ruby',)},
    {'name': 'Express', 'cat': 'framework', 'site': 'expressjs.com',
     'headers': (('x-powered-by', r'^Express'),), 'implies': ('Node.js',)},
    # Der Server-Header allein beweist Flask nicht -- Werkzeug traegt auch eine
    # blanke WSGI-Anwendung. Eindeutig ist dagegen das signierte Sitzungscookie:
    # Flask legt es unter dem Namen 'session' ab, der Wert ist
    # <Nutzlast>.<Zeitstempel>.<Signatur> aus itsdangerous und beginnt mit 'eyJ'
    # (JSON) oder '.eJ' (zlib-gepackt, daher der fuehrende Punkt).
    #
    # Ein JWT sieht genauso aus -- gleiche drei Abschnitte, ebenfalls 'eyJ'.
    # Der Unterschied steckt im ersten Abschnitt: bei Flask ist er der
    # Sitzungsinhalt ({"a":1} -> eyJhIjoxfQ), beim JWT der Kopf mit alg/typ
    # ({"alg":"HS256",...} -> eyJhbGciOi..., {"typ":"JWT",...} -> eyJ0eXAi...).
    # Ohne diesen Ausschluss meldete jeder Express-Dienst, der sein JWT unter
    # dem Namen 'session' ablegt, faelschlich Flask. Die gepackte Form mit
    # fuehrendem Punkt gibt es beim JWT gar nicht.
    {'name': 'Flask', 'cat': 'framework', 'site': 'flask.palletsprojects.com',
     'cookie_value': ((
         'session',
         r'^(?:\.e[Jy]|eyJ(?!hbGciOi|0eXAi))[\w-]+\.[\w-]+\.[\w-]+$'),),
     'implies': ('Python',)},
    {'name': 'Yii', 'cat': 'framework', 'site': 'yiiframework.com',
     'cookie': (r'^YII_CSRF_TOKEN', r'^_csrf'), 'implies': ('PHP',)},
    {'name': 'Phoenix', 'cat': 'framework', 'site': 'phoenixframework.org',
     'html': (r'phx-(?:socket|main)',)},

    # -- JS-Bibliotheken ------------------------------------------------
    {'name': 'React', 'cat': 'js', 'site': 'react.dev',
     'html': (r'data-reactroot|__REACT_DEVTOOLS', r'_reactListening'),
     'script': (r'/react(?:-dom)?(?:@|\.|-)(?P<v>\d+[\d.]*)[^/]*\.js',)},
    {'name': 'Vue.js', 'cat': 'js', 'site': 'vuejs.org',
     'html': (r'data-v-[0-9a-f]{8}', r'__VUE__'),
     'script': (r'/vue(?:@|\.|-)(?P<v>\d+[\d.]*)[^/]*\.js',)},
    {'name': 'Angular', 'cat': 'js', 'site': 'angular.dev',
     'html': (r'ng-version="(?P<v>[\d.]+)"', r'_nghost-|_ngcontent-'),
     'script': (r'/(?:main|polyfills|runtime)\.[0-9a-f]{8,}\.js',)},
    {'name': 'Svelte', 'cat': 'js', 'site': 'svelte.dev',
     'html': (r'svelte-[a-z0-9]{6}',)},
    {'name': 'Preact', 'cat': 'js', 'site': 'preactjs.com',
     'script': (r'/preact(?:@|\.|-)',)},
    {'name': 'jQuery', 'cat': 'js', 'site': 'jquery.com',
     'script': (r'jquery[.-](?P<v>\d+\.\d+[\d.]*)(?:\.min)?\.js', r'/jquery(?:\.min)?\.js'),
     'html': (r'jQuery\.fn\.jquery',)},
    {'name': 'Alpine.js', 'cat': 'js', 'site': 'alpinejs.dev',
     'script': (r'alpinejs',), 'html': (r'\sx-data=',)},
    {'name': 'htmx', 'cat': 'js', 'site': 'htmx.org',
     'script': (r'htmx(?:\.org)?[@.-]?(?P<v>\d+[\d.]*)?(?:\.min)?\.js',),
     'html': (r'\shx-(?:get|post|target)=',)},
    {'name': 'Lodash', 'cat': 'js', 'site': 'lodash.com',
     'script': (r'lodash(?:\.min)?\.js',)},
    {'name': 'Moment.js', 'cat': 'js', 'site': 'momentjs.com',
     'script': (r'moment(?:\.min)?\.js',)},
    {'name': 'Three.js', 'cat': 'js', 'site': 'threejs.org',
     'script': (r'three(?:\.min)?\.js',)},
    {'name': 'GSAP', 'cat': 'js', 'site': 'gsap.com',
     'script': (r'gsap(?:\.min)?\.js', r'TweenMax')},
    {'name': 'Swiper', 'cat': 'js', 'site': 'swiperjs.com',
     'script': (r'swiper[.-]',), 'html': (r'swiper-(?:wrapper|slide)',)},
    {'name': 'Modernizr', 'cat': 'js', 'site': 'modernizr.com',
     'script': (r'modernizr',)},

    # -- CSS ------------------------------------------------------------
    {'name': 'Bootstrap', 'cat': 'css', 'site': 'getbootstrap.com',
     'script': (r'bootstrap(?:[.-](?P<v>\d+\.\d+[\d.]*))?(?:\.min)?\.(?:css|js)',),
     'html': (r'class="[^"]*\b(?:col-md-\d|navbar-toggler)\b',)},
    {'name': 'Tailwind CSS', 'cat': 'css', 'site': 'tailwindcss.com',
     'script': (r'tailwind',),
     'html': (r'class="[^"]*\b(?:flex\s+items-center|text-sm\s+font-medium)\b',)},
    {'name': 'Bulma', 'cat': 'css', 'site': 'bulma.io',
     'script': (r'bulma(?:\.min)?\.css',)},
    {'name': 'Foundation', 'cat': 'css', 'site': 'get.foundation',
     'script': (r'foundation(?:\.min)?\.css',)},
    {'name': 'Font Awesome', 'cat': 'css', 'site': 'fontawesome.com',
     'script': (r'font-?awesome',), 'html': (r'class="fa[srlbd]?\s+fa-',)},
    {'name': 'Google Fonts', 'cat': 'font', 'site': 'fonts.google.com',
     'script': (r'fonts\.(?:googleapis|gstatic)\.com',)},
    {'name': 'Adobe Fonts', 'cat': 'font', 'site': 'fonts.adobe.com',
     'script': (r'use\.typekit\.net',)},

    # -- Webserver / Laufzeit --------------------------------------------
    {'name': 'nginx', 'cat': 'server', 'site': 'nginx.org',
     'headers': (('server', r'^nginx(?:/(?P<v>[\d.]+))?'),)},
    {'name': 'Apache', 'cat': 'server', 'site': 'httpd.apache.org',
     'headers': (('server', r'^Apache(?:/(?P<v>[\d.]+))?'),)},
    {'name': 'LiteSpeed', 'cat': 'server', 'site': 'litespeedtech.com',
     'headers': (('server', r'LiteSpeed'), ('x-litespeed-cache', r'.'))},
    {'name': 'Microsoft IIS', 'cat': 'server', 'site': 'iis.net',
     'headers': (('server', r'^Microsoft-IIS(?:/(?P<v>[\d.]+))?'),)},
    {'name': 'Caddy', 'cat': 'server', 'site': 'caddyserver.com',
     'headers': (('server', r'^Caddy'),)},
    {'name': 'OpenResty', 'cat': 'server', 'site': 'openresty.org',
     'headers': (('server', r'^openresty(?:/(?P<v>[\d.]+))?'),)},
    {'name': 'Apache Tomcat', 'cat': 'server', 'site': 'tomcat.apache.org',
     'headers': (('server', r'Apache-Coyote|Tomcat'),),
     'cookie': (r'^JSESSIONID',), 'implies': ('Java',)},
    {'name': 'Jetty', 'cat': 'server', 'site': 'eclipse.dev',
     'headers': (('server', r'^Jetty'),), 'implies': ('Java',)},
    {'name': 'Envoy', 'cat': 'server', 'site': 'envoyproxy.io',
     'headers': (('server', r'^envoy'),)},
    {'name': 'Traefik', 'cat': 'server', 'site': 'traefik.io',
     'headers': (('x-traefik-router', r'.'),)},
    {'name': 'HAProxy', 'cat': 'server', 'site': 'haproxy.org',
     'cookie': (r'^SERVERID',), 'headers': (('server', r'^haproxy'),)},
    {'name': 'Varnish', 'cat': 'server', 'site': 'varnish-cache.org',
     'headers': (('x-varnish', r'.'), ('via', r'varnish'))},
    {'name': 'Gunicorn', 'cat': 'server', 'site': 'gunicorn.org',
     'headers': (('server', r'^gunicorn(?:/(?P<v>[\d.]+))?'),),
     'implies': ('Python',)},
    {'name': 'Uvicorn', 'cat': 'server', 'site': 'uvicorn.org',
     'headers': (('server', r'^uvicorn'),), 'implies': ('Python',)},
    # Werkzeugs eingebauter Server ist ein Entwicklungsserver. Wer ihn oeffentlich
    # betreibt, hat kein Verbindungslimit und keinen Timeout -- der Fund ist also
    # mehr als eine Namensnennung.
    {'name': 'Werkzeug', 'cat': 'server', 'site': 'werkzeug.palletsprojects.com',
     'headers': (('server', r'^Werkzeug(?:/(?P<v>[\d.]+))?'),),
     'implies': ('Python',)},
    {'name': 'Waitress', 'cat': 'server', 'site': 'docs.pylonsproject.org',
     'headers': (('server', r'^waitress(?:/(?P<v>[\d.]+))?'),),
     'implies': ('Python',)},
    {'name': 'Kestrel', 'cat': 'server', 'site': 'microsoft.com',
     'headers': (('server', r'^Kestrel'),), 'implies': ('ASP.NET',)},
    {'name': 'Google Frontend', 'cat': 'server', 'site': 'cloud.google.com',
     'headers': (('server', r'^(?:gws|Google Frontend|ESF)$'),)},
    {'name': 'Amazon S3', 'cat': 'server', 'site': 'aws.amazon.com',
     'headers': (('server', r'^AmazonS3$'),)},
    {'name': 'GitHub Pages', 'cat': 'hosting', 'site': 'pages.github.com',
     'headers': (('server', r'^GitHub\.com$'),)},

    # -- Sprache / Plattform ---------------------------------------------
    {'name': 'PHP', 'cat': 'language', 'site': 'php.net',
     'headers': (('x-powered-by', r'^PHP(?:/(?P<v>[\d.]+))?'),),
     'cookie': (r'^PHPSESSID',)},
    {'name': 'ASP.NET', 'cat': 'language', 'site': 'dotnet.microsoft.com',
     'headers': (('x-aspnet-version', r'(?P<v>[\d.]+)'),
                 ('x-powered-by', r'ASP\.NET')),
     'cookie': (r'^ASP\.NET_SessionId', r'^\.AspNetCore'),
     'html': (r'__VIEWSTATE',)},
    {'name': 'Java', 'cat': 'language', 'site': 'java.com',
     'cookie': (r'^JSESSIONID',)},
    {'name': 'Node.js', 'cat': 'language', 'site': 'nodejs.org',
     'headers': (('x-powered-by', r'^Express|Next\.js|Nuxt'),)},
    {'name': 'Python', 'cat': 'language', 'site': 'python.org',
     'headers': (('server', r'gunicorn|uvicorn|Werkzeug|waitress'),
                 # Werkzeug nennt die Python-Version gleich mit:
                 # "Werkzeug/3.1.8 Python/3.14.7".
                 ('server', r'Python/(?P<v>[\d.]+)'))},
    {'name': 'Ruby', 'cat': 'language', 'site': 'ruby-lang.org',
     'headers': (('x-powered-by', r'Phusion Passenger'),)},

    # -- CDN / Hosting / Schutz -------------------------------------------
    {'name': 'Cloudflare', 'cat': 'cdn', 'site': 'cloudflare.com',
     'headers': (('cf-ray', r'.'), ('server', r'^cloudflare$')),
     'cookie': (r'^__cf', r'^cf_clearance')},
    {'name': 'Fastly', 'cat': 'cdn', 'site': 'fastly.com',
     'headers': (('x-served-by', r'cache-'), ('x-fastly-request-id', r'.'))},
    {'name': 'Akamai', 'cat': 'cdn', 'site': 'akamai.com',
     'headers': (('x-akamai-transformed', r'.'), ('server', r'^AkamaiGHost'))},
    {'name': 'Amazon CloudFront', 'cat': 'cdn', 'site': 'aws.amazon.com',
     'headers': (('x-amz-cf-id', r'.'), ('via', r'CloudFront'))},
    {'name': 'Vercel', 'cat': 'hosting', 'site': 'vercel.com',
     'headers': (('x-vercel-id', r'.'), ('server', r'^Vercel$'))},
    {'name': 'Netlify', 'cat': 'hosting', 'site': 'netlify.com',
     'headers': (('x-nf-request-id', r'.'), ('server', r'^Netlify'))},
    {'name': 'Cloudflare Pages', 'cat': 'hosting', 'site': 'pages.dev',
     'headers': (('cf-pages-deployment-id', r'.'),)},
    {'name': 'Azure Front Door', 'cat': 'cdn', 'site': 'azure.microsoft.com',
     'headers': (('x-azure-ref', r'.'),)},
    {'name': 'Google Cloud CDN', 'cat': 'cdn', 'site': 'cloud.google.com',
     'headers': (('via', r'1\.1 google'),)},
    {'name': 'KeyCDN', 'cat': 'cdn', 'site': 'keycdn.com',
     'headers': (('server', r'^keycdn-engine'),)},
    {'name': 'Bunny.net', 'cat': 'cdn', 'site': 'bunny.net',
     'headers': (('server', r'^BunnyCDN'),)},
    {'name': 'Imperva Incapsula', 'cat': 'waf', 'site': 'imperva.com',
     'headers': (('x-iinfo', r'.'),), 'cookie': (r'^incap_ses', r'^visid_incap')},
    {'name': 'Sucuri', 'cat': 'waf', 'site': 'sucuri.net',
     'headers': (('x-sucuri-id', r'.'),)},
    {'name': 'Cloudflare Turnstile', 'cat': 'captcha', 'site': 'cloudflare.com',
     'script': (r'challenges\.cloudflare\.com/turnstile',)},
    {'name': 'reCAPTCHA', 'cat': 'captcha', 'site': 'google.com',
     'script': (r'(?:www\.google\.com|recaptcha\.net)/recaptcha/',)},
    {'name': 'hCaptcha', 'cat': 'captcha', 'site': 'hcaptcha.com',
     'script': (r'hcaptcha\.com/1/api\.js',)},
    {'name': 'Friendly Captcha', 'cat': 'captcha', 'site': 'friendlycaptcha.com',
     'script': (r'friendlycaptcha',)},

    # -- Messung / Reichweite ---------------------------------------------
    {'name': 'Google Analytics 4', 'cat': 'analytics', 'site': 'analytics.google.com',
     'script': (r'gtag/js\?id=G-',), 'html': (r'gtag\(.{0,20}G-[A-Z0-9]{6,}',)},
    {'name': 'Google Tag Manager', 'cat': 'tagmanager', 'site': 'tagmanager.google.com',
     'script': (r'googletagmanager\.com/gtm\.js',),
     'html': (r'GTM-[A-Z0-9]{4,}',)},
    {'name': 'Matomo', 'cat': 'analytics', 'site': 'matomo.org',
     'script': (r'matomo\.js|piwik\.js',), 'html': (r'_paq\.push',)},
    {'name': 'Plausible', 'cat': 'analytics', 'site': 'plausible.io',
     'script': (r'plausible\.io/js/',)},
    {'name': 'Fathom', 'cat': 'analytics', 'site': 'usefathom.com',
     'script': (r'cdn\.usefathom\.com',)},
    {'name': 'Umami', 'cat': 'analytics', 'site': 'umami.is',
     'script': (r'umami\.js|/script\.js.{0,40}data-website-id',),
     'html': (r'data-website-id=',)},
    {'name': 'Microsoft Clarity', 'cat': 'analytics', 'site': 'clarity.microsoft.com',
     'script': (r'clarity\.ms',)},
    {'name': 'Hotjar', 'cat': 'analytics', 'site': 'hotjar.com',
     'script': (r'static\.hotjar\.com',)},
    {'name': 'Mixpanel', 'cat': 'analytics', 'site': 'mixpanel.com',
     'script': (r'cdn\.mxpnl\.com',)},
    {'name': 'Amplitude', 'cat': 'analytics', 'site': 'amplitude.com',
     'script': (r'amplitude',)},
    {'name': 'Segment', 'cat': 'analytics', 'site': 'segment.com',
     'script': (r'cdn\.segment\.com',)},
    {'name': 'Adobe Analytics', 'cat': 'analytics', 'site': 'adobe.com',
     'script': (r'/b/ss/|omniture|adobedtm',)},
    {'name': 'etracker', 'cat': 'analytics', 'site': 'etracker.com',
     'script': (r'static\.etracker\.com',)},
    {'name': 'Yandex Metrica', 'cat': 'analytics', 'site': 'metrica.yandex.com',
     'script': (r'mc\.yandex\.ru',)},
    {'name': 'Cloudflare Web Analytics', 'cat': 'analytics', 'site': 'cloudflare.com',
     'script': (r'static\.cloudflareinsights\.com',)},
    {'name': 'Piwik PRO', 'cat': 'analytics', 'site': 'piwik.pro',
     'script': (r'\.piwik\.pro/',)},

    # -- Werbung / Vermarktung --------------------------------------------
    {'name': 'Google AdSense', 'cat': 'marketing', 'site': 'google.com',
     'script': (r'pagead2\.googlesyndication\.com',)},
    {'name': 'Google Ad Manager', 'cat': 'marketing', 'site': 'google.com',
     'script': (r'securepubads\.g\.doubleclick\.net',)},
    {'name': 'Meta Pixel', 'cat': 'marketing', 'site': 'facebook.com',
     'script': (r'connect\.facebook\.net/.{0,20}/fbevents\.js',),
     'html': (r'fbq\(.{0,10}init',)},
    {'name': 'LinkedIn Insight', 'cat': 'marketing', 'site': 'linkedin.com',
     'script': (r'snap\.licdn\.com',)},
    {'name': 'TikTok Pixel', 'cat': 'marketing', 'site': 'tiktok.com',
     'script': (r'analytics\.tiktok\.com',)},
    {'name': 'Taboola', 'cat': 'marketing', 'site': 'taboola.com',
     'script': (r'cdn\.taboola\.com',)},
    {'name': 'Outbrain', 'cat': 'marketing', 'site': 'outbrain.com',
     'script': (r'widgets\.outbrain\.com',)},
    {'name': 'Criteo', 'cat': 'marketing', 'site': 'criteo.com',
     'script': (r'static\.criteo\.net',)},
    {'name': 'Mailchimp', 'cat': 'marketing', 'site': 'mailchimp.com',
     'script': (r'chimpstatic\.com|list-manage\.com',)},
    {'name': 'Klaviyo', 'cat': 'marketing', 'site': 'klaviyo.com',
     'script': (r'static\.klaviyo\.com',)},

    # -- Einwilligung -----------------------------------------------------
    {'name': 'Cookiebot', 'cat': 'consent', 'site': 'cookiebot.com',
     'script': (r'consent\.cookiebot\.com',)},
    {'name': 'OneTrust', 'cat': 'consent', 'site': 'onetrust.com',
     'script': (r'cdn\.cookielaw\.org|onetrust',)},
    {'name': 'Usercentrics', 'cat': 'consent', 'site': 'usercentrics.com',
     'script': (r'app\.usercentrics\.eu|privacy-proxy\.usercentrics\.eu',)},
    {'name': 'Borlabs Cookie', 'cat': 'consent', 'site': 'borlabs.io',
     'script': (r'borlabs-cookie',), 'cookie': (r'^borlabs-cookie',)},
    {'name': 'CookieYes', 'cat': 'consent', 'site': 'cookieyes.com',
     'script': (r'cdn-cookieyes\.com',)},
    {'name': 'Complianz', 'cat': 'consent', 'site': 'complianz.io',
     'script': (r'/plugins/complianz',)},
    {'name': 'Klaro', 'cat': 'consent', 'site': 'klaro.org',
     'script': (r'klaro(?:\.min)?\.js',)},

    # -- Bezahlen / Kontakt / Medien --------------------------------------
    {'name': 'Stripe', 'cat': 'payment', 'site': 'stripe.com',
     'script': (r'js\.stripe\.com',)},
    {'name': 'PayPal', 'cat': 'payment', 'site': 'paypal.com',
     'script': (r'(?:www\.)?paypal(?:objects)?\.com/',)},
    {'name': 'Klarna', 'cat': 'payment', 'site': 'klarna.com',
     'script': (r'x\.klarnacdn\.net',)},
    {'name': 'Mollie', 'cat': 'payment', 'site': 'mollie.com',
     'script': (r'js\.mollie\.com',)},
    {'name': 'Adyen', 'cat': 'payment', 'site': 'adyen.com',
     'script': (r'checkoutshopper-live\.adyen\.com',)},
    {'name': 'Intercom', 'cat': 'support', 'site': 'intercom.com',
     'script': (r'widget\.intercom\.io',)},
    {'name': 'Zendesk', 'cat': 'support', 'site': 'zendesk.com',
     'script': (r'static\.zdassets\.com',)},
    {'name': 'Crisp', 'cat': 'support', 'site': 'crisp.chat',
     'script': (r'client\.crisp\.chat',)},
    {'name': 'tawk.to', 'cat': 'support', 'site': 'tawk.to',
     'script': (r'embed\.tawk\.to',)},
    {'name': 'HubSpot', 'cat': 'support', 'site': 'hubspot.com',
     'script': (r'js\.hs-scripts\.com|js\.hsforms\.net',)},
    {'name': 'Userlike', 'cat': 'support', 'site': 'userlike.com',
     'script': (r'userlike-cdn-widgets',)},
    {'name': 'YouTube', 'cat': 'media', 'site': 'youtube.com',
     'html': (r'(?:www\.)?youtube(?:-nocookie)?\.com/embed/',)},
    {'name': 'Vimeo', 'cat': 'media', 'site': 'vimeo.com',
     'html': (r'player\.vimeo\.com/video/',)},
    {'name': 'Video.js', 'cat': 'media', 'site': 'videojs.com',
     'script': (r'video(?:-js|js)[.-]',)},
    {'name': 'Wistia', 'cat': 'media', 'site': 'wistia.com',
     'script': (r'fast\.wistia\.(?:net|com)',)},
    {'name': 'Google Maps', 'cat': 'media', 'site': 'maps.google.com',
     'script': (r'maps\.google(?:apis)?\.com',),
     'html': (r'google\.com/maps/embed',)},
    {'name': 'Leaflet', 'cat': 'media', 'site': 'leafletjs.com',
     'script': (r'leaflet(?:\.min)?\.(?:js|css)',)},
    {'name': 'Mapbox', 'cat': 'media', 'site': 'mapbox.com',
     'script': (r'api\.mapbox\.com',)},
    {'name': 'OpenStreetMap', 'cat': 'media', 'site': 'openstreetmap.org',
     'html': (r'tile\.openstreetmap\.org',)},
    {'name': 'Algolia', 'cat': 'search', 'site': 'algolia.com',
     'script': (r'algolia(?:net|\.net|search)',)},
)

# ── DNS-Seite ────────────────────────────────────────────────────────────────

# Auf das *Ende* des Nameserver-Namens geprüft, nie als Teilstring -- sonst
# würde "cloudflare.com.angreifer.net" als Cloudflare durchgehen.
NS_SUFFIXES = (
    ('ns.cloudflare.com', 'Cloudflare DNS'),
    ('awsdns-00.com', 'Amazon Route 53'),
    ('awsdns.com', 'Amazon Route 53'),
    ('awsdns.org', 'Amazon Route 53'),
    ('awsdns.net', 'Amazon Route 53'),
    ('awsdns.co.uk', 'Amazon Route 53'),
    ('googledomains.com', 'Google Cloud DNS'),
    ('google.com', 'Google Cloud DNS'),
    ('azure-dns.com', 'Azure DNS'),
    ('azure-dns.net', 'Azure DNS'),
    ('azure-dns.org', 'Azure DNS'),
    ('azure-dns.info', 'Azure DNS'),
    ('digitalocean.com', 'DigitalOcean DNS'),
    ('hetzner.com', 'Hetzner DNS'),
    ('hetzner.de', 'Hetzner DNS'),
    ('ui-dns.com', 'IONOS'),
    ('ui-dns.de', 'IONOS'),
    ('ui-dns.org', 'IONOS'),
    ('ui-dns.biz', 'IONOS'),
    ('netcup.net', 'Netcup'),
    ('netcup.de', 'Netcup'),
    ('stratoserver.net', 'STRATO'),
    ('strato.de', 'STRATO'),
    ('domaincontrol.com', 'GoDaddy'),
    ('registrar-servers.com', 'Namecheap'),
    ('dns-parking.com', 'Hostinger'),
    ('desec.io', 'deSEC'),
    ('gandi.net', 'Gandi'),
    ('ovh.net', 'OVH'),
    ('inwx.de', 'INWX'),
    ('inwx.eu', 'INWX'),
    ('all-inkl.com', 'ALL-INKL'),
    ('kasserver.com', 'ALL-INKL'),
    ('mijndomein.nl', 'Mijndomein'),
    ('transip.net', 'TransIP'),
    ('dnsimple.com', 'DNSimple'),
    ('nsone.net', 'NS1'),
    ('dnsmadeeasy.com', 'DNS Made Easy'),
    ('cloudns.net', 'ClouDNS'),
    ('dynect.net', 'Oracle Dyn'),
    ('ultradns.com', 'Vercara UltraDNS'),
    ('ultradns.net', 'Vercara UltraDNS'),
    ('core-networks.de', 'Core Networks'),
    ('hosteurope.de', 'Host Europe'),
    ('schlundtech.de', 'SchlundTech'),
    ('bunny.net', 'Bunny DNS'),
    ('he.net', 'Hurricane Electric'),
    ('akam.net', 'Akamai Edge DNS'),
    ('vercel-dns.com', 'Vercel DNS'),
    ('wixdns.net', 'Wix DNS'),
    ('shopifydns.com', 'Shopify DNS'),
    ('squarespacedns.com', 'Squarespace DNS'),
    ('github.com', 'GitHub'),
)

# Ein include: im SPF-Eintrag sagt, wer für die Domain Mails verschicken darf --
# das ist in der Praxis die zuverlässigste Spur auf die benutzten Dienste,
# weil sie im Gegensatz zu einem Skript-Pfad nicht vom Seitenaufbau abhängt.
SPF_INCLUDES = (
    ('_spf.google.com', 'Google Workspace'),
    ('spf.protection.outlook.com', 'Microsoft 365'),
    ('servers.mcsv.net', 'Mailchimp'),
    ('spf.mandrillapp.com', 'Mailchimp (Mandrill)'),
    ('sendgrid.net', 'SendGrid'),
    ('amazonses.com', 'Amazon SES'),
    ('mailgun.org', 'Mailgun'),
    ('spf.sendinblue.com', 'Brevo'),
    ('spf.brevo.com', 'Brevo'),
    ('spf.mtasv.net', 'Postmark'),
    ('zoho.eu', 'Zoho Mail'),
    ('zoho.com', 'Zoho Mail'),
    ('_spf.salesforce.com', 'Salesforce'),
    ('spf.hubspotemail.net', 'HubSpot'),
    ('_spf.klaviyo.com', 'Klaviyo'),
    ('spf.messagingengine.com', 'Fastmail'),
    ('mailjet.com', 'Mailjet'),
    ('helpscoutemail.com', 'Help Scout'),
    ('shops.shopify.com', 'Shopify'),
    ('_spf.qualtrics.com', 'Qualtrics'),
    ('spf.zendesk.com', 'Zendesk'),
    ('_spf.intercom.io', 'Intercom'),
    ('_spf.pardot.com', 'Salesforce Pardot'),
    ('mktomail.com', 'Adobe Marketo'),
    ('_spf.cleverreach.com', 'CleverReach'),
    ('rsgsv.net', 'Mailchimp'),
    ('spf.rapidmail.de', 'rapidmail'),
    ('_spf.mailingwork.de', 'mailingwork'),
    ('cmail.com', 'Campaign Monitor'),
    ('spf.antispameurope.com', 'Hornetsecurity'),
    ('spf.perfora.net', 'IONOS'),
    ('_spf.kundenserver.de', 'IONOS'),
    ('_spf.strato.de', 'STRATO'),
    ('_spf.udag.de', 'united-domains'),
)
