name: Webtop XFCE
description: Debian XFCE Desktop zugänglich über jeden modernen Webbrowser, mit Firefox, Thunderbird und vielen weiteren Programmen vorinstalliert
version: "1.8.22"
slug: ubuntu_webtop
init: false

arch:
  - aarch64
  - amd64

# Hardware-Zugriff
audio: false
video: true
udev: true
tmpfs: true

privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
  - SYS_PTRACE

devices:
  - /dev/dri
  - /dev/dri/card0
  - /dev/dri/card1
  - /dev/dri/renderD128
  - /dev/fuse

# Ports
ports:
  3000/tcp: 7776
  3001/tcp: 7777

ports_description:
  3000/tcp: Web Interface HTTP (Host-Port 7776)
  3001/tcp: Web Interface HTTPS (Host-Port 7777)

# Speicher-Mounts — addon_config ist persistent über Updates hinweg
map:
  - addon_config:rw
  - share:rw
  - media:rw
  - backup:rw
  - ssl

# Standardwerte für Umgebungsvariablen
environment:
  TITLE: Ubuntu Webtop
  START_DOCKER: "false"
  PULSE_SERVER: "unix:/tmp/pulse-runtime/native"

# Benutzer-Optionen
options:
  PUID: 1000
  PGID: 1000
  TZ: "Europe/Berlin"
  PASSWORD: ""
  show_media: false
  show_backup: false
  smb_1_server: ""
  smb_1_share: ""
  smb_1_user: ""
  smb_1_password: ""
  smb_2_server: ""
  smb_2_share: ""
  smb_2_user: ""
  smb_2_password: ""
  smb_3_server: ""
  smb_3_share: ""
  smb_3_user: ""
  smb_3_password: ""
  smb_4_server: ""
  smb_4_share: ""
  smb_4_user: ""
  smb_4_password: ""
  smb_5_server: ""
  smb_5_share: ""
  smb_5_user: ""
  smb_5_password: ""
  nfs_1_server: ""
  nfs_1_share: ""
  nfs_2_server: ""
  nfs_2_share: ""
  nfs_3_server: ""
  nfs_3_share: ""

schema:
  PUID: int
  PGID: int
  TZ: match([A-Z][a-z]*/[A-Za-z0-9_]*)?
  PASSWORD: str?
  KEYBOARD: list(da-dk-qwerty|de-de-qwertz|en-gb-qwerty|en-us-qwerty|es-es-qwerty|fr-ch-qwertz|fr-fr-azerty|it-it-qwerty|ja-jp-qwerty|pt-br-qwerty|sv-se-qwerty|tr-tr-qwerty)?
  DRINODE: list(/dev/dri/card0|/dev/dri/card1|/dev/dri/renderD128|/dev/dri/renderD129)?
  show_media: bool
  show_backup: bool
  smb_1_server: str?
  smb_1_share: str?
  smb_1_user: str?
  smb_1_password: str?
  smb_2_server: str?
  smb_2_share: str?
  smb_2_user: str?
  smb_2_password: str?
  smb_3_server: str?
  smb_3_share: str?
  smb_3_user: str?
  smb_3_password: str?
  smb_4_server: str?
  smb_4_share: str?
  smb_4_user: str?
  smb_4_password: str?
  smb_5_server: str?
  smb_5_share: str?
  smb_5_user: str?
  smb_5_password: str?
  nfs_1_server: str?
  nfs_1_share: str?
  nfs_2_server: str?
  nfs_2_share: str?
  nfs_3_server: str?
  nfs_3_share: str?

panel_icon: mdi:monitor
panel_admin: false

url: https://github.com/LuckyTriple7/HA-AddOns
