name: FileBox
description: Web-Oberfläche zum Hoch- und Herunterladen von Dateien in /share/filebox
version: "0.0.5"
slug: filebox
url: https://github.com/LuckyTriple7/HA-AddOns

arch:
  - amd64

startup: application
boot: manual
init: false

image: "ghcr.io/luckytriple7/filebox"

ingress: true
ingress_port: 17771
panel_icon: mdi:folder-open
panel_title: FileBox

ports:
  17771/tcp: 17771

ports_description:
  17771/tcp: FileBox Web-UI

map:
  - share:rw
  - media:rw
  - config:rw
  - backup:rw

options:
  port: 17771
  username: admin
  password: admin1234567
  show_media: false
  show_config: false
  show_backup: false

schema:
  port: int
  username: str
  password: str
  show_media: bool
  show_config: bool
  show_backup: bool
