name: FileBox
description: Web-Oberfläche zum Hoch- und Herunterladen von Dateien in /share/filebox
version: "1.1.4"
slug: filebox
url: https://github.com/LuckyTriple7/HA-AddOns

arch:
  - amd64

startup: application
boot: manual
init: false

image: "ghcr.io/luckytriple7/filebox"

ingress: true
ingress_port: 17771
panel_icon: mdi:folder-open
panel_title: FileBox

privileged:
  - SYS_ADMIN

apparmor: false

ports:
  17771/tcp: 17771

ports_description:
  17771/tcp: FileBox Web-UI

map:
  - share:rw
  - media:rw
  - config:rw
  - backup:rw

options:
  port: 17771
  username: admin
  password: admin1234567
  show_media: false
  show_config: false
  show_backup: false
  smb_1_server: ""
  smb_1_share: ""
  smb_1_user: ""
  smb_1_password: ""
  smb_2_server: ""
  smb_2_share: ""
  smb_2_user: ""
  smb_2_password: ""
  smb_3_server: ""
  smb_3_share: ""
  smb_3_user: ""
  smb_3_password: ""
  smb_4_server: ""
  smb_4_share: ""
  smb_4_user: ""
  smb_4_password: ""
  smb_5_server: ""
  smb_5_share: ""
  smb_5_user: ""
  smb_5_password: ""

schema:
  port: int
  username: str
  password: str
  show_media: bool
  show_config: bool
  show_backup: bool
  smb_1_server: str?
  smb_1_share: str?
  smb_1_user: str?
  smb_1_password: str?
  smb_2_server: str?
  smb_2_share: str?
  smb_2_user: str?
  smb_2_password: str?
  smb_3_server: str?
  smb_3_share: str?
  smb_3_user: str?
  smb_3_password: str?
  smb_4_server: str?
  smb_4_share: str?
  smb_4_user: str?
  smb_4_password: str?
  smb_5_server: str?
  smb_5_share: str?
  smb_5_user: str?
  smb_5_password: str?
