name: WhatsApp
description: WhatsApp Web als persistente Session mit REST-API und Webhook für Home Assistant
version: "1.5.7"
image: "ghcr.io/luckytriple7/whatsapp"
slug: whatsapp
url: https://github.com/LuckyTriple7/HA-AddOns

arch:
  - amd64
  - aarch64

startup: application
boot: manual
init: false

map:
  - addon_config:rw

ingress: true
ingress_port: 17776
panel_icon: mdi:whatsapp
panel_title: WhatsApp

ports:
  17776/tcp: 17776

ports_description:
  17776/tcp: WhatsApp Web-UI und REST-API

options:
  dark_mode: true
  download_media: false
  webhook_incoming: ""
  initial_chats: 30
  initial_messages: 20
  keep_deleted: false
  debug_mode: false
  ha_notifications: false
  ha_notifications_privacy: false
  ha_notifications_skip_groups: false
  ha_token: ""

schema:
  dark_mode: bool
  download_media: bool
  webhook_incoming: str?
  initial_chats: int?
  initial_messages: int?
  keep_deleted: bool
  debug_mode: bool
  ha_notifications: bool
  ha_notifications_privacy: bool
  ha_notifications_skip_groups: bool
  ha_token: str?
